### ISSUE TITLE
Contents of the pkt is cut

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#161]
_From [vinifa...@gmail.com](https://code.google.com/u/107509585192880620386/) on November 12, 2014 15:17:49_

What steps will reproduce the problem? 
file_in=open('C:\snooperPort.pcap','rb')
for ts, pkt in dpkt.pcap.Reader(file_in):
    eth = dpkt.ethernet.Ethernet(pkt)
    ip = eth.data
    tcp = ip.data
    data = tcp.data
	print data
	print len(pkt) 

What is the expected output? What do you see instead?
 I expected the file "print expected" attached, but I saw the file "print watched steps above" attached. 

What version of the product are you using? On what operating system? 
dkpt-1.8, python 2.7. Win 8.1 (eclipse IDE) 

Please provide any additional information below. 
Why the packets that I am seeing is been cutted with 1506 of length?
I would like to get whole packet with all xml. After that I will parse it.

best regards,

**Attachment:** [print expected.txt print watched steps above.txt](http://code.google.com/p/dpkt/issues/detail?id=135)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=135_

**Comment by sunhao2014** [comment]
Hi @kbandla, it seems that the attachment link can't work properly after URL redirection.

**Comment by kbandla** [comment]
Oh wow. Lets see if we can...

**Comment by sunhao2014** [comment]
In my opinion, the main reason for this issue is the IP fragmentation.

From the expected data (print expected.txt) provided in the attachment, I noticed the length of the TCP data is 3,354 bytes, which exceed the MTU of Ethernet (~1,500 bytes). Furthermore it'll trigger the IP fragmentation. Thus the original message would be segmented into several packets, with the data length of 1506 bytes.

I don't think this is a bug of dpkt, and the user could get the whole packet after IP reassembly.

**Comment by kbandla** [comment]
:+1: go ahead and close this issue.
