### ISSUE TITLE
Status of Python 3 Support

### ISSUE THREAD

**Issue by mhils** [kbandla/dpkt#243]
Hey,

Just wanted to ask what's the current status of Python 3 support.
- http://honeynet.org/node/1313 claims that dpkt 2.0 supports Python 3
- https://pypi.python.org/pypi/dpkt hosts a 1.8 wheel that claims to support Python 3...
- ... but this fails on importing.

So, how do things look actually? :smiley:

**Comment by kbandla** [comment]
@mhils I am yet to merge the python3 branch into mainline. You can try out the `merge_py3` branch if you want to play with it in the interim.

**Comment by RemiDesgrange** [comment]
Hi, I'm trying to make dpkt work with py3. I'm trying it since half and hour now, and I see that I will need to break a lot (like a lot) of things. for example :

* import
* `print`
* `dict` iterations
* metaclass (oh sh*t)

## import
for example the `__init__.py` file

```python
"""fast, simple packet creation and parsing."""
from __future__ import absolute_import

__author__ = 'Dug Song'
__author_email__ = 'dugsong@monkey.org'
__license__ = 'BSD'
__url__ = 'http://dpkt.googlecode.com/'
__version__ = '1.8.8'

```

because `from . import ah` doesn't mean you'll just have to do the old way like `import ah`, you'll need to refactor everything... (`import .ah`) 

## dict

Can we use `items()` ? Because it's slower in python2, but less refactoring or using itertools ?

Thanks

**Comment by obormot** [comment]
@RemiDesgrange FYI PR https://github.com/kbandla/dpkt/pull/305

**Comment by obormot** [comment]
Python 3 support added in release 1.9

**Comment by AndreMiras** [comment]
> Python 3 support added in release 1.9
@obormot good news! However I don't see it released on github or on pypi, the lastest one is 1.8.8, is it actually released or is it only available on master?

**Comment by brifordwylie** [comment]
@AndreMiras we still need to fix Issue 318: https://github.com/kbandla/dpkt/issues/318 before tagging and releasing the python3 support. Anyone want to volunteer for that? just don't have the cycles right now.

**Comment by AndreMiras** [comment]
OK @brifordwylie thank you for your feedback. I've subscribed to the issue, but I won't have time to address it. Good luck!
