### ISSUE TITLE
Error in creating CSV file of Flow information

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#266]
when am trying to create csv file for flow information, giving the following error:

Traceback (most recent call last):
  File "D:/Python27/flowfinal csv.py", line 72, in <module>
    c.writerow(data)
Error: sequence expected
>>> 

here is the code:
https://gist.github.com/sheenawadhwa/07e0bd1f7918ca92f023efc3d8f3d985

**Comment by kbandla** [comment]
@sheenawadhwa , **again**, this is **NOT** an issue in the dpkt project. [stackoverflow.com](stackoverflow.com) is the place to ask these kinds of questions. 

At this point, more than 95% of "your" project code has been written by me. Here is the remaining part: 
https://gist.github.com/kbandla/5785e56804ab705e760b2810e631e90f

Please do not come back here. **Unless** the issue is with code in dpkt itself.

**Comment by sheenawadhwa** [comment]
its just taking input with tkinter but the code is related to dpkt thats y posted here and ur given code is storing no data in csv

**Comment by kbandla** [comment]
@sheenawadhwa : No, the part of the code that deals with dpkt has no 'issues'. It works flawlessly. The problem lies [elsewhere](https://github.com/kbandla/dpkt/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Asheenawadhwa+), and I am not talking about tkinter. 

The code does [write](https://gist.github.com/kbandla/5785e56804ab705e760b2810e631e90f#file-flowcsv-py-L76) to a csv file.
