### ISSUE TITLE
The ord() is not needed for Python3

### ISSUE THREAD

**Issue by berloha** [kbandla/dpkt#483]
File "Python\lib\site-packages\dpkt\ssl.py", line 34, in unpack
    padlen = ord(self.data[0])
TypeError: ord() expected string of length 1, but int found

**Comment by kbandla** [comment]
Can you share the pcap or the ssl packet data that you were trying to parse? Would need it to reproduce the issue

**Comment by berloha** [comment]
https://cloud.mail.ru/public/jc25/d3oys4QsE
Exception on packet #2

**Comment by obormot** [comment]
While this is a valid bug (dpkt should use `compat_ord` instead of plain `ord`), the particular piece of code that crashes sits under `SSL2` class, while the pcap has TLS v1.2.
@berloha, I suggest using `dpkt.ssl.tls_multi_factory(buf)` for better results decoding this; it doesn't crash and returns 3 TLS records correctly.

**Comment by obormot** [comment]
fixed in https://github.com/kbandla/dpkt/pull/484
