### ISSUE TITLE
Move documentation from RST to MD and move hosting from ReadTheDocs to github.io

### ISSUE THREAD

**Issue by brifordwylie** [kbandla/dpkt#503]
Okay, so RST/ReadtheDocs was the 'right thing' when I setup the documentation for DPKT 4-5 years ago (or whenever that was) but we should probably just do the easier MD/github.io. Working with MD is much easier and using github.io means stuff just works and we don't have a special build docs/deploy/etc....

I'll do this at some point in the future. @kbandla @obormot let me know if you have any suggestions/reservations about the switch.

**Comment by tassosblackg** [comment]
Yes, I will agree too.. the documentation needs some serious improvements it's hard to find which method or attribute I need in order to extract info, etc. For someone like me, it's the first time that I'm using dpkt, reading examples helps to a point but I want something like access source port number or package type (with a quick search this, implement like this or call this attribute/object ).

**Comment by brifordwylie** [comment]
@tassosblackg sounds great... go forth and conquer. My suggestion is to follow this fork/PR guide (maybe you already know this stuff) https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Also as part of the doc improvements.. we should actually change the 'contributing' section to include a link/discussion of that ^

Anyway, my suggestion is do a little bit of work, submit the PR.. make sure it looks fine/good with maintainers and then do more work on the same PR. I would hate to have you put in a ton of work, do the PR at the very end and then have it be a 'mismatch' somehow...

**Comment by brifordwylie** [comment]
Okay, so this is now done... all docs are markdown..
